@startuml
!theme carbon-gray
title Offre Opérationnelle

class "[[StructureDefinition-ror-offre-operationnelle.html ROROffreOperationnelle]]" as Offre {
  identifiantOffre : Identifier [1..1]
  nomOffre : string [0..1]
  typeOffre : Coding [0..*]
  champActivite : Coding [1..1]
  modePriseEnCharge : Coding [1..1]
  uniteSensible : boolean [1..1]
  temporaliteAccueil : Coding [0..*]
  modaliteAccueil : Coding [0..*]
  modeGestion : Coding [0..1]
  acteSpecifique : Coding [0..*]
  specialisationPriseEnCharge : Coding [0..*]
  ouvertureAnnuelle : Coding [0..*]
  professionRessource : Coding [0..*]
  competenceSpecifique : Coding [0..*]
  niveauExpertise : Coding [0..*]
  typeFermeture : Coding [0..1]
  horaire : Horaire [0..*]
  contact : Contact [0..*]
  boiteLettreMSS : BoiteLettreMSS [0..*]
  metadonnee : RORMetadonnee [1..1]
}

class "[[StructureDefinition-ror-activite-operationnelle.html RORActiviteOperationnelle]]" as AO {
  activiteOperationnelle : Coding [1..1]
  familleActiviteOperationnelle : Coding [0..1]
  metadonnee : RORMetadonnee [1..1]
}

class "[[StructureDefinition-ror-patientele.html RORPatientele]]" as Pat {
  ageMin : Quantity [1..1]
  ageMax : Quantity [1..1]
  publicPrisEnCharge : Coding [0..*]
}

package "Ressources Opérationnelles" as R_pkg {
  class "[[StructureDefinition-ror-lieu-realisation-offre.html RORLieuRealisationOffre]]" as Lieu
}

package "Professionnel" as P_pkg {
  class "[[StructureDefinition-ror-situation-operationnelle.html RORSituationOperationnelle]]" as SitOp
}

Offre "1" --> "0..*" AO : décrit par
Offre "1" --> "0..1" Pat : pour
Offre "1" --> "1" Lieu : réalisée dans
Offre "1" --> "0..*" SitOp : réalisée par

@enduml
