@startuml
!theme carbon-gray
title Ressources Opérationnelles

package "Offre Opérationnelle" as Off_pkg {
  class "[[StructureDefinition-ror-offre-operationnelle.html ROROffreOperationnelle]]" as Offre
}

class "[[StructureDefinition-ror-lieu-realisation-offre.html RORLieuRealisationOffre]]" as Lieu {
  idExterneSynchro : Identifier [0..1]
  nomExterneSynchro : string [0..1]
  commentaire : string [0..1]
  metadonnee : RORMetadonnee [1..1]
}

class "[[StructureDefinition-ror-equipement-specifique.html ROREquipementSpecifique]]" as Equip {
  typeEquipement : Coding [1..1]
  nbEquipementEnService : integer [0..1]
  metadonnee : RORMetadonnee [1..1]
}

class "[[StructureDefinition-ror-capacite-prise-charge.html RORCapacitePriseCharge]]" as CPC {
  affectationTemporaire : Coding [1..1]
  commentaire : string [0..1]
  metadonnee : RORMetadonnee [1..1]
}

class "[[StructureDefinition-ror-capacite-accueil-operationnelle.html RORCapaciteAccueilOperationnelle]]" as CAO {
  natureCapacite : Coding [1..1]
  nombreCapacite : integer [0..1]
  statutCapacite : Coding [1..1]
  temporaliteCapacite : Coding [1..1]
  typeSourceCapacite : Coding [0..1]
  genreCapaciteDispo : Coding [0..1]
  typeFermetureCapacite : Coding [0..1]
  typeLitSupplementaire : Coding [0..*]
  typeCrise : Coding [0..*]
}

class "[[StructureDefinition-ror-capacite-habitation.html RORCapaciteHabitation]]" as CH {
  typeHabitation : Coding [1..1]
  nbHabitation : integer [0..1]
  metadonnee : RORMetadonnee [1..1]
}

Offre "1" --> "1" Lieu : réalisée dans
Lieu "1" --> "0..*" Equip : dispose de
Lieu "1" --> "0..*" CPC : capacité de
CPC "1" --> "0..*" CAO : détaillée par
Offre "1" --> "0..*" CH : hébergement

@enduml
