@startuml
!theme carbon-gray
title Tarif

abstract class "[[StructureDefinition-ror-tarif.html RORTarif]]" as Tarif {
  typeTarif : Coding [1..1]
  montantTarif : Money [1..1]
  unitePrix : Coding [1..1]
  dateDebutValiditeTarif : date [0..1]
  metadonnee : RORMetadonnee [1..1]
}

class "[[StructureDefinition-ror-forfait-socle-hebergement.html RORForfaitSocleHebergement]]" as FSH {
  prestationsNonObligatoiresIncluses : Coding [0..*]
  autresPrestationsNonObligatoiresIncluses : string [0..*]
  tarifMoins60Ans : boolean [1..1]
  typeHabitation : Coding [1..1]
  conditionTarifaire : Coding [0..1]
  temporaliteAccueil : Coding [1..1]
}

class "[[StructureDefinition-ror-tarif-accueil-de-jour.html RORTarifAccueilDeJour]]" as TAJ {
  conditionTarifaire : Coding [0..1]
}

class "[[StructureDefinition-ror-tarif-dependance.html RORTarifDependance]]" as TD {
  groupeTarifaireDependance : Coding [1..1]
  temporaliteAccueil : Coding [1..1]
}

class "[[StructureDefinition-ror-tarif-aides-humaines.html RORTarifAidesHumaines]]" as TAH {
  nomTarifAidesHumaines : string [0..1]
  conditionTarifaire : Coding [0..1]
  modeGestion : Coding [1..1]
}

class "[[StructureDefinition-ror-tarif-prestation-supplementaire.html RORTarifPrestationSupplementaire]]" as TPS {
  nomAutrePrestationSupp : string [1..1]
  nomPrestationSupp : Coding [0..1]
}

class "[[StructureDefinition-ror-supplement-tarif-hebergement.html RORSupplementTarifHebergement]]" as STH {
  typeHabitation : Coding [1..1]
}

class "[[StructureDefinition-ror-tarif-portage-repas.html RORTarifPortageRepas]]" as TPR {
  conditionTarifaire : Coding [0..1]
  nomTarifPortageRepas : string [0..1]
}

Tarif <|-- FSH
Tarif <|-- TAJ
Tarif <|-- TD
Tarif <|-- TAH
Tarif <|-- TPS
Tarif <|-- STH
Tarif <|-- TPR

@enduml
