@startuml
!theme carbon-gray
title Vue d'ensemble du modèle ROR

package "Structure" as S {
  class "[[StructureDefinition-ror-entite-juridique.html ROREntiteJuridique]]" as EJ
  class "[[StructureDefinition-ror-entite-geographique.html ROREntiteGeographique]]" as EG
}

package "Organisation" as O {
  class "[[StructureDefinition-ror-organisation-interne.html ROROrganisationInterne]]" as OI
}

package "Tarif" as T {
  abstract class "[[StructureDefinition-ror-tarif.html RORTarif]]" as Tarif
}

package "Offre Opérationnelle" as Off {
  class "[[StructureDefinition-ror-offre-operationnelle.html ROROffreOperationnelle]]" as Offre
}

package "Ressources Opérationnelles" as R {
  class "[[StructureDefinition-ror-lieu-realisation-offre.html RORLieuRealisationOffre]]" as Lieu
}

package "Professionnel" as P {
  class "[[StructureDefinition-ror-situation-operationnelle.html RORSituationOperationnelle]]" as SitOp
  class "[[StructureDefinition-ror-exercice-professionnel.html RORExerciceProfessionnel]]" as EP
}

EJ "1" --> "1..*" EG
EG "1" --> "0..*" OI
EG "1" --> "0..*" Tarif
OI "0..1" --> "1..*" Offre
OI "*" --> "*" OI : contient
Offre "1" --> "1" Lieu
Offre "1" --> "0..*" SitOp
SitOp "0..*" --> "1" EP : réalisée par

@enduml
