# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.test.ror
canonical: https://interop.esante.gouv.fr/ig/fhir/test-ror
name: TestROR
title: "Démonstration - Modèle Logique ROR dérivant du MOS"
description: "IG de démonstration illustrant comment définir des modèles logiques ROR qui dérivent des modèles logiques du MOS (Modèle des Objets de Santé)."
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build

jurisdiction: urn:iso:std:iso:3166#FR "France (la)"

dependencies:
  ans.fr.mos: 0.1.0-ballot
  hl7.fhir.uv.xver-r5.r4: 0.1.0

groups:
  ReglesDéGestion:
    name: "Règles de gestion"
    description: "Instances Requirements regroupant les règles de gestion RG_EXP_* du modèle d'exposition ROR"
    resources:
      - Basic/ror-requirements-structure
      - Basic/ror-requirements-organisation
      - Basic/ror-requirements-offre-operationnelle
      - Basic/ror-requirements-tarif
      - Basic/ror-requirements-ressources-operationnelles
      - Basic/ror-requirements-professionnel
      - Basic/ror-requirements-classes-communes

parameters:
    shownav: 'true'
    path-expansion-params: '../../expansion-params.json'
    pin-canonicals: pin-all
    apply-contact: true
    logging:
      - progress
    i18n-default-lang: fr
    apply-jurisdiction: true

pages:
    index.md:
        title: Accueil
    avantages-ml.md:
        title: Pourquoi le Modèle Logique HL7 ?
    fonctionnalites-ror.md:
        title: Fonctionnalités disponibles pour le ROR
    classes-communes.md:
        title: Classes Communes
    structure.md:
        title: Structure
    organisation.md:
        title: Organisation
    offre-operationnelle.md:
        title: Offre Opérationnelle
    tarif.md:
        title: Tarif
    ressources-operationnelles.md:
        title: Ressources Opérationnelles
    professionnel.md:
        title: Professionnel Ressource
    regles-de-gestion.md:
        title: Règles de gestion
    change-log.md:
        title: Historique des versions

menu:
    Accueil: index.html
    Contexte:
        Pourquoi le Modèle Logique HL7 ?: avantages-ml.html
        Fonctionnalités pour le ROR: fonctionnalites-ror.html
    Modèle d'exposition:
        Classes Communes: classes-communes.html
        Structure: structure.html
        Organisation: organisation.html
        Offre Opérationnelle: offre-operationnelle.html
        Tarif: tarif.html
        Ressources Opérationnelles: ressources-operationnelles.html
        Professionnel Ressource: professionnel.html
    Règles de gestion: regles-de-gestion.html
    Ressources de conformité: artifacts.html
    Historique: change-log.html
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
