classDiagram
    namespace MOS {
        class MOS_EJ["EntiteJuridique"]
        class MOS_EG["EntiteGeographique"]
    }

    class EJ["ROREntiteJuridique"] {
        idNatStruct : Identifier [1..1]
        numFINESS : Identifier [0..1]
        numSIREN : Identifier [0..1]
        raisonSociale : string [1..1]
        complementRaisonSociale : string [0..1]
        statutJuridique : Coding [1..1]
        agregatStatutJuridiqueNiv2 : Coding [0..1]
        adresseEJ : Address [0..1]
        contact : Contact [0..*]
        dateCreation : date [0..1]
        dateFermeture : date [0..1]
        typeFermeture : Coding [0..1]
        metadonnee : RORMetadonnee [1..1]
    }

    class EG["ROREntiteGeographique"] {
        idNatStruct : Identifier [1..1]
        numFINESS : Identifier [0..1]
        raisonSociale : string [1..1]
        categorieEtablissement : Coding [0..*]
        modaliteParticipationSPH : Coding [0..1]
        accessibiliteLieu : Coding [0..*]
        niveauRecoursORSAN : Coding [0..*]
        aideFinanciere : Coding [0..*]
        typeFermeture : Coding [0..1]
        territoireSante : Identifier [0..1]
        dateCreation : date [0..1]
        dateFermeture : date [0..1]
        metadonnee : RORMetadonnee [1..1]
    }

    namespace Organisation {
        class OI["ROROrganisationInterne"]
    }
    namespace TarifPkg {
        class Tarif["RORTarif"] {
            &lt;&lt;abstract&gt;&gt;
        }
    }

    EJ --|> MOS_EJ
    EG --|> MOS_EG

    EJ "1" --> "1..*" EG
    EG "1" --> "0..*" OI
    EG "1" --> "0..*" Tarif

    click EJ href "StructureDefinition-ror-entite-juridique.html" "ROREntiteJuridique"
    click EG href "StructureDefinition-ror-entite-geographique.html" "ROREntiteGeographique"
    click OI href "StructureDefinition-ror-organisation-interne.html" "ROROrganisationInterne"
    click Tarif href "StructureDefinition-ror-tarif.html" "RORTarif"

    classDef mosClass fill:#D3D3D3
    classDef mosClass stroke:#888
    classDef mosClass color:#333
    cssClass "MOS_EJ,MOS_EG" mosClass
