classDiagram
    namespace Structure {
        class EJ["ROREntiteJuridique"]
        class EG["ROREntiteGeographique"]
    }
    namespace Organisation {
        class OI["ROROrganisationInterne"]
    }
    namespace TarifPkg {
        class Tarif["RORTarif"] {
            &lt;&lt;abstract&gt;&gt;
        }
    }
    namespace OffreOperationnelle {
        class Offre["ROROffreOperationnelle"]
    }
    namespace RessourcesOperationnelles {
        class Lieu["RORLieuRealisationOffre"]
    }
    namespace Professionnel {
        class SitOp["RORSituationOperationnelle"]
        class EP["RORExerciceProfessionnel"]
    }

    EJ "1" --> "1..*" EG
    EG "1" --> "0..*" OI
    EG "1" --> "0..*" Tarif
    OI "0..1" --> "1..*" Offre
    OI "*" --> "*" OI : contient
    Offre "1" --> "1" Lieu
    Offre "1" --> "0..*" SitOp
    SitOp "0..*" --> "1" EP : réalisée par

    click EJ href "StructureDefinition-ror-entite-juridique.html" "ROREntiteJuridique"
    click EG href "StructureDefinition-ror-entite-geographique.html" "ROREntiteGeographique"
    click OI href "StructureDefinition-ror-organisation-interne.html" "ROROrganisationInterne"
    click Tarif href "StructureDefinition-ror-tarif.html" "RORTarif"
    click Offre href "StructureDefinition-ror-offre-operationnelle.html" "ROROffreOperationnelle"
    click Lieu href "StructureDefinition-ror-lieu-realisation-offre.html" "RORLieuRealisationOffre"
    click SitOp href "StructureDefinition-ror-situation-operationnelle.html" "RORSituationOperationnelle"
    click EP href "StructureDefinition-ror-exercice-professionnel.html" "RORExerciceProfessionnel"
